INSERT INTO USERS (ID, FULL_NAME, EMAIL, PASSWORD) VALUES (0, 'admin', 'admin', STRINGDECODE('x61Ey612Kl2gpFL56FT9weDnpSo4AV8j8+qx2AuTHdRyY036xxzTTrw10Wq3+4qQyB+XURPWx1ON\nxp3Y3pB37A=='));
INSERT INTO ROLES (ID, NAME, DESCRIPTION) VALUES (0, 'admin', 'admin');
INSERT INTO ROLES (ID, NAME, DESCRIPTION) VALUES (1, 'user', 'user');
INSERT INTO USERS_ROLES (USER_ID, ROLE_ID) VALUES (0, 0);



